### ISSUE TITLE
Resource manifest wiki article

### ISSUE THREAD

**Issue by carltonwhitehead** [carltonwhitehead/coner#13]

**Comment by carltonwhitehead** [comment]
Work in progress: https://github.com/carltonwhitehead/coner/wiki/Resource-Manifest

**Comment by carltonwhitehead** [comment]
Lots of content on https://github.com/carltonwhitehead/coner/wiki/Resource-Manifest now. Please review

**Comment by jshort** [comment]
Looks good, thanks!  Is 'handicap' a generic name for PAX?

**Comment by carltonwhitehead** [comment]
Yes. I wanted to use a generic term for a couple reasons

1. PAX sux
2. Not everyone uses PAX

**Comment by jshort** [comment]
The WHOLE goal of my comment above was to make you say what you said in bullet 1 above :).

**Comment by carltonwhitehead** [comment]
I thought so. Happy to oblige

**Comment by carltonwhitehead** [comment]
Paging @akrikos

**Comment by akrikos** [comment]
At first glance, it seems nicely coherent. I'll need to think on things some more, but I worry about the edge cases that we won't find until we start building a full application.

I do have a couple of nitpicks on naming: 'Class' seems a bit autocross specific. 'Category' feels so generic as to be difficult to understand. May I propose that we name these things by their intended purpose?
* For Class, I like 'Handicap Group'
* For Category, I like 'Competition Group' - who you're competing against

I'm not enamored with the term 'group', but can't think of a better term off the top of my head.

One last thing... /sessions/~ is one character shorter and more geeky :-)

**Comment by carltonwhitehead** [comment]
Coner is an autocross event operations system. With that in mind, I think it's OK if we bake some autocross-isms into the public API. However, I'm inclined to agree in the case of changing Class/Category to Handicap/Competition Group. Class and Category are particular to SCCA style autocross, and I think it'll be easy enough to deliver that abstraction with little more than terminology change. That's why I used "Handicap" rather than "PAX" in the first place.

I used the term "Set" a lot instead of list or group. It seems like "Competition Set" and "Category Set" could work too.

/sessions/~ is pretty awesome. Might need to do that one too :)

Thanks for all the suggestions.

**Comment by carltonwhitehead** [comment]
I forgot to address your point about edge cases this morning. I fully expect we'll find some edge cases that will require changes to the public API. I think we can safely consider the public API specification to be a living document until we're closer to a release. If we need to change it, we will.

I'll try to find some time this weekend to revise the article to incorporate the suggestions. If everything is still looking good to everyone after that, I'd like to start creating one feature issue per resource line item and get back to coding.

**Comment by carltonwhitehead** [comment]
I've plugged in a bunch of changes to this document. Please take another look. Here's [the diff](https://github.com/carltonwhitehead/coner/wiki/Resource-Manifest/_compare/9faa6423ac776a1f1443c4f5787649b2f7e421f2...19bcc1316137b91ef0d75b7d56cfa3741afa86ae?diff=unified)

**Comment by akrikos** [comment]
`/events/results/grouped` could be represented by `/events/results?groupBy=:groupTypeName`
Will we ever want to segment the results by both competitionGroup and handicapGroup? It seems like most of the time we'll want competitionGroup but include raw and handicapped times.

Do we want to design in a method for re-runs? Maybe mark a run as not counting? Mark a driver as getting an extra run for the competition? That feels like a second pass sort of feature as it's not strictly needed to run an event (the organizers can just allow another run for said car), but it might be good to add a note about thoughts as an addendum to the doc or something. I guess this goes into the category of "things to do that would help run an event more smoothly". Like set a 'max runs' number but then add exceptions for certain cars or something. </ramble>

**Comment by akrikos** [comment]
I'll stop nitpicking now I swear. It's close enough.

**Comment by carltonwhitehead** [comment]
@akrikos I was expecting the `/events/results/grouped` resource would return the results grouped by handicap and competition group according to the `grouping` property of the competition group. For example, for a competition group with `grouping == true`, the results would include all competitors in the competition group (how our Novice class works).  In the case of a competition group with `grouping == false`, grouping would happen at the Handicap Group level (how Open classes work). Does that address your concern?

Counterpoint to the above: this is essentially reimplimenting the approach of a particular commercial offering. The time to explore a better approach is now.

Also similar to the approach of a particular commercial offering, I was planning to implement reruns as a value for the penalty property of a run. This is probably not ideal. Perhaps it would make more sense to make it a boolean property instead. While iterating a list of all run entities, it would be much more efficient to compute the official run number with a boolean property comparision than a string comparison.

I think it would make sense to put a maxRunCount property on the event entity. Perhaps a registration could optionally override it in case some club wants to run a pay twice drive twice model.

**Comment by carltonwhitehead** [comment]
I updated the resource manifest with input from our meeting last night. Here's [the diff](https://github.com/carltonwhitehead/coner/wiki/Resource-Manifest/_compare/19bcc1316137b91ef0d75b7d56cfa3741afa86ae...45ffea71478b1dafe9552127dd2cad4ca390fdbd).

**Comment by carltonwhitehead** [comment]
I think this has been reviewed thoroughly enough already, so I'm going to go ahead and get started entering one feature issue per resource/verb. If you find anything missing, please reopen this issue and comment.
