### ISSUE TITLE
POST /handicapGroups

### ISSUE THREAD

**Issue by carltonwhitehead** [carltonwhitehead/coner#53]
add a handicap group

**Comment by jshort** [comment]
@carltonwhitehead thoughts on changing the REST URIs from camelcase to underscore separated?  I realized I haven't worked with a REST API with camelcase URIs and I checked out twitter, dropbox, google maps, etsy and they all use underscores.

**Comment by carltonwhitehead** [comment]
What do we stand to gain/lose by changing to underscores vs not changing? "other people do it this way" doesn't seem like a strong justification for change. According to [RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.2.3), the relevant part of the URI is case sensitive, so having them in camel case isn't going to break HTTP specs or introducing some unpredictable behavior by having camel case. When we get the API spec generator up and running, it'll be clear to anyone using what the case will be.

**Comment by jshort** [comment]
Nothing to gain/lose other than effectively following a 'styleguide' but with respect to URI format.

**Comment by jshort** [comment]
@carltonwhitehead Thoughts on handicapFactor type and constraints.  Right now I have it as BigDecimal and constrained between 0 and 1.

**Comment by carltonwhitehead** [comment]
BigDecimal from 0 to 1 seems like a good fit.
