### ISSUE TITLE
Integrate API doc generator

### ISSUE THREAD

**Issue by carltonwhitehead** [carltonwhitehead/coner#86]
It looks like there is a project that implements a dropwizard swagger bundle at https://github.com/federecio/dropwizard-swagger

**Comment by carltonwhitehead** [comment]
https://github.com/federecio/dropwizard-swagger doesn't (yet?) support the v0.8 series of dropwizard that we're using (release candidates and snapshots). I don't see anything in their issue tracker indicating that they're planning to upgrade. Perhaps that will change when the v0.8 series of dropwizard is released. I'm going to backburner this

**Comment by carltonwhitehead** [comment]
I added an issue on their issue tracker, see federecio/dropwizard-swagger#30

**Comment by carltonwhitehead** [comment]
It looks like someone fixed this. Just waiting for their PR to get merged https://github.com/federecio/dropwizard-swagger/pull/40

**Comment by Moonchopper** [comment]
Added Dropwizard-Swagger - compiles successfully. Created example annotation under /resource/EventsResource class -- API entries will not show up until Swagger/API/JAX-RS annotations are put in place (don't forget to import needed libraries from com.wordnik.swagger.annotations.*)

Annotation notes here: https://github.com/swagger-api/swagger-core/wiki/Annotations
